#! /bin/sh
chmod -x complexpolylongdiv.dtx
pdflatex -shell-escape complexpolylongdiv.dtx
pdflatex -shell-escape complexpolylongdiv.dtx
pdflatex -shell-escape complexpolylongdiv.dtx
mkdir complexpolylongdiv
mv complexpolylongdiv.pdf README complexpolylongdiv.dtx complexpolylongdiv.ins complexpolylongdiv
zip -r complexpolylongdiv complexpolylongdiv
rm -r complexpolylongdiv
rm *.idx *.out *.toc *.ilg *.ind *.hd *.aux *.log *.sty *.tex